ABP:
  max:
    th: 240
    window_size: 5
    stride: 1

  min:
    th: -10
    window_size: 5
    stride: 1

  line:
    th: 0.1
    window_size: 10
    stride: 10

  peaks:
    th: 0.8
    window_size: 5
    stride: 1
ICP:
  max:
    th: 250
    window_size: 5
    stride: 1

  min:
    th: -10
    window_size: 5
    stride: 1

  line:
    th: 0.1
    window_size: 10
    stride: 10

  peaks:
    th: 1.00
    window_size: 5
    stride: 1

merge:
  distance: 1
  overlap: 0.3
