distance: 1
ABP:
  max:
    th: 300
    window_size: 5
    stride: 1

  min:
    th: -5
    window_size: 5
    stride: 1

  line:
    th: 0.15
    window_size: 10
    stride: 10

  peaks:
    th: 0.8
    window_size: 5
    stride: 1
ICP:
  max:
    th: 250
    window_size: 5
    stride: 1

  min:
    th: -10
    window_size: 5
    stride: 1

  line:
    th: 0.1
    window_size: 10
    stride: 10

  peaks:
    th: 0.9
    window_size: 5
    stride: 1